import java.io.IOException;
class Demo {
	
	public static void main(String[] args) {
		
		try {
			
			
		}catch(InterruptedException | IOException e) {

		}
	}
}

/**
 * Even though InterruptedException and IOException both are checked exceptions. And never thrown out of given try block
 * 
 * Error is shown only for the one on left side
 * exception InterruptedException is never thrown in body of corresponding try statement
 */
